export type Language = "en" | "sn" | "zu";

export type RemittanceStatus =
    | "QUEUED"              // Offline mode: waiting in browser queue[cite: 12]
    | "INITIATED"           // Sent to Gateway[cite: 12]
    | "IN_TRANSIT"          // Processing at payout partner[cite: 12]
    | "READY_FOR_COLLECTION" // Pickup ready[cite: 12]
    | "COLLECTED";          // Collected in Harare[cite: 12]

export interface Transaction {
    id: string;             // Unique Transfer ID[cite: 12]
    senderName: string;
    receiverName: string;
    receiverPhone: string;
    sendAmountZAR: number;
    receiveAmountUSD: number;
    exchangeRate: number;
    feeZAR: number;
    status: RemittanceStatus;
    createdAt: string;
    pickupCode: string;
    translatedReceipt?: string; // Generated by Vambo AI proxy[cite: 12]
    smsDelivered?: boolean;     // Simulated SMS delivery indicator[cite: 12]
}

export interface FxRate {
    zarToUsd: number;
    usdToZar?: number;
    lastUpdated?: string;
}

export interface FxRate {
    zarToUsd: number;
    usdToZar?: number;
    lastUpdated?: string;
    trend?: string;
}